// aws r2
export enum AWS_R2 {
  R2_REGION = 'R2_REGION',
  R2_ACCESS_KEY_ID = 'R2_ACCESS_KEY_ID',
  R2_SECRET_ACCESS_KEY = 'R2_SECRET_ACCESS_KEY',
  R2_BUCKET = 'R2_BUCKET',
  R2_URL = 'R2_URL',
  R2_ENDPOINT = 'R2_ENDPOINT',
  R2_DEFAULT_REGION = 'R2_DEFAULT_REGION',
}