// aws ses email
export enum AWS_SES_EMAIL {
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
  AWS_REGION = 'AWS_REGION',
  AWS_SES_FROM_EMAIL = 'AWS_SES_FROM_EMAIL',
}