// lambda aws 提供的无服务器计算服务 可以进行一些下载，本身业务是进行处理 网页绘制 pdf 然后下载的服务
export enum LAMBDA {
  LAMBDA_SIDECAR_APP_NAME = 'LAMBDA_SIDECAR_APP_NAME',
  LAMBDA_SIDECAR_ENV = 'LAMBDA_SIDECAR_ENV',
  LAMBDA_SIDECAR_ACCESS_KEY_ID = 'LAMBDA_SIDECAR_ACCESS_KEY_ID',
  LAMBDA_SIDECAR_SECRET_ACCESS_KEY = 'LAMBDA_SIDECAR_SECRET_ACCESS_KEY',
  LAMBDA_SIDECAR_REGION = 'LAMBDA_SIDECAR_REGION',
  LAMBDA_SIDECAR_ARTIFACT_BUCKET_NAME = 'LAMBDA_SIDECAR_ARTIFACT_BUCKET_NAME',
  LAMBDA_SIDECAR_EXECUTION_ROLE = 'LAMBDA_SIDECAR_EXECUTION_ROLE',
  LAMBDA_SIDECAR_PREFIX = 'LAMBDA_SIDECAR_PREFIX',
  LAMBDA_SIDECAR_FUNCTION_NAME = 'LAMBDA_SIDECAR_FUNCTION_NAME',
}