// lambda
export enum LAMBDA {
  LAMBDA_SIDECAR_APP_NAME = 'LAMBDA_SIDECAR_APP_NAME',
  LAMBDA_SIDECAR_ENV = 'LAMBDA_SIDECAR_ENV',
  LAMBDA_SIDECAR_ACCESS_KEY_ID = 'LAMBDA_SIDECAR_ACCESS_KEY_ID',
  LAMBDA_SIDECAR_SECRET_ACCESS_KEY = 'LAMBDA_SIDECAR_SECRET_ACCESS_KEY',
  LAMBDA_SIDECAR_REGION = 'LAMBDA_SIDECAR_REGION',
  LAMBDA_SIDECAR_ARTIFACT_BUCKET_NAME = 'LAMBDA_SIDECAR_ARTIFACT_BUCKET_NAME',
  LAMBDA_SIDECAR_EXECUTION_ROLE = 'LAMBDA_SIDECAR_EXECUTION_ROLE',
  LAMBDA_SIDECAR_PREFIX = 'LAMBDA_SIDECAR_PREFIX',
  LAMBDA_SIDECAR_FUNCTION_NAME = 'LAMBDA_SIDECAR_FUNCTION_NAME',
}