// redis
export enum REDIS {
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_USERNAME = 'REDIS_USERNAME',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_DB = 'REDIS_DB',
  REDIS_TTL = 'REDIS_TTL',
  REDIS_PREFIX = 'REDIS_PREFIX',
}